[tool.briefcase]
project_name = "MDUYoutube"
bundle = "com.example"
version = "2024.10.10"
url = "https://mdu.uppriez.net"
license.file = "LICENSE"
author = 'Nawapon Boonjua'
author_email = "info.neixproducer@gmail.com"

[tool.briefcase.app.mduyt]
formal_name = "Youtube Downloader"
description = "A minimalist YouTube Downloader built with Qt, allowing users to easily download videos from YouTube."
icon = "icon/win/icon.ico" # Briecase will choose the right extension depending the os (png,ico,...)
sources = ['src/mduyt']
requires = ['PySide6==6.7.2',
            'PySide6_Addons==6.7.2',
            'PySide6_Essentials==6.7.2',
            'certifi==2024.8.30',
            'charset-normalizer==3.3.2',
            'idna==3.10',
            'lief==0.15.1',
            'requests==2.32.3',
            'shiboken6==6.7.2',
            'urllib3==2.2.3']


